### ISSUE TITLE
R integration Q's

### ISSUE THREAD

**Issue by sierra-alpha** [Rasqualius/SNP_comparisons#2]
How would you normally call the R version from within R?

is the input file already saved as a file?

Ideally I'd like to have the documentation allow R users to call this from within R, but still get the performance benifits from the cpp code. seems quite possible, just need to know how you do it currently. 

A code snippet of R code calling your R SNP_comparisons would be perfect.

**Comment by laninsky** [comment]
Ha, yup. I've done a terrible job documenting it so far. The basic R syntax is: 
```
SNP_mismatch <- function(working_dir,input_structure_file) {
do some stuff
}
```
After this function is loaded into R (easiest way is literally copying and pasting it into the R console), folks would invoke the function by:
```
SNP_mismatch(working_dir,input_structure_file)
```
Where working_dir and input_structure_file will be replaced by their specific working directory and the name of the structure file within that working directory. The input is already saved as that structure file (because it is a relatively common file type used for other analyses too).

**Comment by sierra-alpha** [comment]
I think I need to install R and play around.

The output of your call would display graphically?

Do you have an example of a structure file you could post here?

Ideally, I would like to have the code be able to run independently as an executable and also from within R, what's your take on its use case? How would you imagine it is most useful to you and your colleagues?

**Comment by laninsky** [comment]
Heyo - I've attached a structure file. Individuals are in rows (two rows per individual b/c diploid organisms have two copies of each SNP, one inherited from their mum, one from their dad), SNP positions are in columns. -9 = missing data, 0 = A, 1 = C, 2 = G, and 3 = T (the DNA nucleotides):
[project_data.txt](https://github.com/Sierra-Alpha/SNP_comparisons/files/3353366/project_data.txt)

I think the code just running on its own and not through R would be best, because then people don't need to worry about having R installed in order to run it (less dependencies that way). It is fairly common to run biology-ish programs on the command line by invoking their name, and then passing arguments via flags, so something like that? Using R for the plotting might be easier though, than trying to reinvent the wheel on this.

The R code outputs a tab-delimited text file with the following columns:  
sample1 = name of the first sample being compared  
sample2 = name of the second sample being compared  
total_SNPs = number of SNPs (i.e. columns) where both individuals have information (e.g. neither sample has a -9)  
mismatched_SNPs = number of non-missing SNPs that don't match up between samples
mismatch_perc = the % of mismatching SNPs (e.g. mismatched SNPs/total_SNPs\*100)
mismatch_both_hets = of the SNPs that have mismatches between the two individuals, what number are heterozygous in both individuals (e.g. within each sample, the "mum" copy and the "dad" copy are not the same)  
both_hets_perc = the % of this out of the total number of mismatches (e.g. mismatch_both_hets/mismatched_SNPs\*100)  
mismatch_both_homs = of the SNPs that have mismatches between the two individuals, what number are homozygous in both individuals (e.g. within each sample, the "mum" copy and the "dad"  *are* the same)   
mismatch_both_homs_perc =  the % of this out of the total number of mismatches (e.g. mismatch_both_homs/mismatched_SNPs\*100)  
mismatch_het_hom = of the SNPs that have mismatches between the two individuals, what number are homozygous in one individual and heterozygous in the other  
non_both_hets_perc_het_hom = what is the % of this category.  

The code also outputs a plot summarizing this info with the mismatch_perc on the y-axis, the x-axis showing total_SNPs, and each dot representing each row of the table (e.g. each pairwise comparison between samples), coloured by non_both_hets_perc_het_hom, and dots sized by mismatch_both_hets e.g. 
[plot_of_mismatches.pdf](https://github.com/Sierra-Alpha/SNP_comparisons/files/3353410/plot_of_mismatches.pdf)

Thanks for looking into this!

**Comment by sierra-alpha** [comment]
Okay cool we’ll my code already does what you need from within C so I should just include some instructions and finish off the documentation to make it useable.

As far as the graphical output I might be able to tweak your R code to call this C code so it runs fast and then graphically displays the request.

So I’ll make the steps to

1. Change the code to accept command line arguments.

2. Write the documentation

3. Figure out how to call it within R and display graphically. (I may pass this one back to you)

4. Make it multithreaded so it runs even faster :)

Coolies!

**Comment by laninsky** [comment]
Sounds good - I can tweak the documentation too after you get it going to explain the "biology" side (seeing as I never got a readme going for the original... slacker!). Yass, on the multithreading too!!!

**Comment by sierra-alpha** [comment]
Okay so I did it backward, 

1. made it multithreaded, 
2. changed to accept command line args
3. writing the documentation now
4. I will leave it for you to integrate how you see best into R

So if you don't mind I'll close this issue now?
